In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Cracion de una matriz y un vector

In [8]:
A = np.array([[1,2],
              [5,3]])

In [7]:
print(A)

[[1 2]
 [5 3]]


In [9]:
b = np.array([7,8])

In [10]:
print(b)

[7 8]


In [11]:
print(A[:,0])

[1 5]


In [12]:
print(A[:,1])

[2 3]


In [13]:
b = b.T

In [14]:
print(b)

[7 8]


In [15]:
A = A.T

In [16]:
print(A)

[[1 5]
 [2 3]]


In [17]:
C = A*b

In [18]:
print(C)

[[ 7 40]
 [14 24]]


In [19]:
C = A@b

In [20]:
print(C)

[47 38]


In [21]:
C = np.dot(A,b)

In [22]:
print(C)

[47 38]


In [23]:
I = np.eye(3)

In [24]:
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
D = np.diag([1,2,3])

In [27]:
print(D)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [28]:
Inv = np.linalg.inv(D)

In [29]:
print(Inv)

[[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]]


In [30]:
t = np.trace(D)

In [31]:
print(t)

6


In [32]:
L1 = np.linalg.norm(D,1)

In [33]:
print(L1)

3.0


In [34]:
L2 = np.linalg.norm(D,2)

In [35]:
print(L2)

3.0


In [37]:
G = np.linspace(0,100,10)

In [38]:
print(G)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
